name: "Load Dependency Graph"

on:
  push:
    branches:
      - "master"
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scan-dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: Alfresco/alfresco-build-tools/.github/actions/maven-dependency-scan@v18.15.0
        with:
          java-version: '21'
          maven-version: '3.9.9'
          maven-args: -Dscopes=compile,runtime
          maven-username: ${{ secrets.NEXUS_USERNAME }}
          maven-password: ${{ secrets.NEXUS_PASSWORD }}
          maven-settings-path: ".ci.settings.xml"